pipeline {
    agent any
    tools {         
        maven 'Apache-maven-3.8.8'              
    }
    stages {
        // stage('Mvn install'){
        //     steps{
        //         sh 'mvn clean install'
        //     }
        // }
        stage("version"){
            steps{
                sh "python3 --version"
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage("Try Python"){
            steps{
                script{
                    String a = "Hi"
                    String b = "We"
                    python(script: '''
                    from jenkins import pythtest
                    pythtest.callFunc(${a}, ${b})
                    ''')
//                    def scriptOutput = sh(returnStdout: true, script: 'python3 jenkins/pythtest.py.callFunc(${a}, ${b})').trim()
                    echo "${a}"
                    echo "${b}"
                    echo "Script output: ${scriptOutput}"
                }
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        stage('Complete'){
            steps{
                echo 'Job Complete!'
            }
        }
    }
}
