pipeline {
    agent any
    tools {         
        maven 'Apache-maven-3.8.8'              
    }
    stages {
        // stage('Mvn install'){
        //     steps{
        //         sh 'mvn clean install'
        //     }
        // }
        stage("version"){
            steps{
                sh "python3 --version"
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage("Try Python"){
            steps{
                script{
                    def a
                    def b
//                    sh"""
//                    variable = python3 jenkins/pythtest.py
//                    variable.callFunc(${a}, ${b})
//                    """
 //                   variable = sh "python3 -c 'import pythtest; pythtest.callFunc()'"
  //                  def scriptOutput = sh(returnStdout: true, script: '${variable} ${a}, ${b}').trim()
                    def cmd = '''cd jenkins && python3 -c 'import pythtest; pythtest.callFunc(a, b)' '''
                    def proc = ["/bin/sh", "-c", cmd].execute()
                    proc.waitFor()
                    def scriptOutput = "return code: ${proc.exitValue()}"
   //                 def scriptOutput = sh(returnStdout: true, script: 'python3 jenkins/pythtest.py callFunc a b').trim()
                    def l = scriptOutput.substring(1, scriptOutput.length()-1).split(',').collect{it as Object}
  //                  def scriptOutput = sh(returnStdout: true, script: 'python3 jenkins/pythtest.py sum_fn 5 8').trim()
                    a = l[0]
                    b = l[1]
                    echo "Script output: ${scriptOutput}"
                    echo "Script output1: ${l}"
                    echo "${a}"
                    echo "${b}"
                }
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        stage('Complete'){
            steps{
                echo 'Job Complete!'
            }
        }
    }
}
